[commands."compile:presentation"]
command = "node presentation/src/parser.js --dir=presentation"
description = "Compile presentation"
visible = false

[commands.install]
command = "npm install"
description = "Install project dependencies"
dependsOn = [ "install:reveal" ]

[commands."install:reveal"]
command = "npm install"
cwd = "./submodules/presentation"
description = "Install reveal.js dependencies"
visible = false

[commands."compile:rollup"]
command = "rollup -c rollup.config.js"
binPath = "./node_modules/.bin"
description = "Start rollup server and watch app/ directory"
visible = false

[commands."start:reveal"]
command = "npm start -- --port=${port}"
cwd = "./submodules/presentation"
description = "Start reveal server"
variables = { port = "8000" }
visible = false

[concurrents.presentation]
commands = [ "compile:presentation -w", "start:reveal" ]
description = "Run presentation at http://localhost:8000"

[concurrents.compile]
commands = [ "compile:presentation -c", "compile:rollup" ]
description = "Compile presentation and samples"

[concurrents.start]
commands = [ "compile:rollup -w" ]
description = "Run samples at http://localhost:3000"
