imports = [ "./Commands-hidden.toml" ]

[concurrents.install]
commands = [ "install_project", "install_slides" ]
description = "Install dependencies"

[concurrents.start]
commands = [ "slides --var.port=8000", "rollup -w" ]
description = "Run rollup"